### ISSUE TITLE
Config-problem

### ISSUE THREAD

**Issue by haglind** [popeen/Home-Assistant-Addon-MotalaVattenAvfall#2]
Funkar denna som den ska fortfarande? Jag har försökt med alla möjliga kombinationer men antar att jag gör något fel. 

Vilket format på adress och type ska det vara?

**Comment by popeen** [comment]
Sorry för sent svar, nej de hade bytt API så den var stendöd.
Fixat det nu på morgonen så om du uppdaterar till version 0.1.1 så ska den funka igen

Ang adressen, gå in i appen och sök efter din adress så passt precis att du bara får ett resultat i listan, den söksträngen kan du använda som adress. 

type ska vara Kärl 1, Kärl 2 eller Slam
